# Generated by Django 4.0.4 on 2022-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
