# Generated by Django 4.0.4 on 2022-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_announcement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.ManyToManyField(to='ads.location'),
        ),
    ]
